language: python
python:
  - "3.9"

# Install dependencies
install:
  - pip install -r requirements.txt

# Run tests and checks
script:
  # Check code formatting with black
  - black --check .
  # Run flake8 linter
  - flake8 .
  # Run Django tests with coverage
  - coverage run --source='.' manage.py test
  # Generate coverage report
  - coverage report
  # Report coverage to coveralls
  - coveralls

# Deploy to AWS Elastic Beanstalk on successful build
# deploy:
#   provider: elasticbeanstalk
#   region: us-east-1
#   app: se_django_hello_world
#   env: django-polls-prod
#   bucket_name: elasticbeanstalk-us-east-1-183631324450
#   access_key_id: $AWS_ACCESS_KEY_ID
#   secret_access_key: $AWS_SECRET_ACCESS_KEY
#   on:
#     branch: main

# Cache pip dependencies
cache: pip

# Set environment variables for Django
env:
  - DJANGO_SETTINGS_MODULE=myAPP_SEfall2025.settings
  - SECRET_KEY=test-secret-key-for-travis
