# Generated by Django 5.2.6 on 2025-10-15 16:52

from django.db import migrations
from django.contrib.auth.models import User


def create_admin_user(apps, schema_editor):
    """Create admin superuser if it doesn't exist"""
    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser(
            username="admin",
            email="admin@example.com",
            password="admin123",  # Change this in production!
        )


def reverse_create_admin_user(apps, schema_editor):
    """Remove admin user"""
    User.objects.filter(username="admin").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_create_admin_user),
    ]
